### ISSUE TITLE
Trouble with `pads_callback.jl`. Can't get message data to display to stdout

### ISSUE THREAD

**Issue by anandijain** [wookay/PushInterface.jl#1]
Hello!

Thanks a bunch for making this package. I've been trying to do some stuff with MIDI, Julia, and my Push 2.
Your rtmidi wrapper is immensly helpful. 

I was able to get `set_led.jl` to work perfectly, but not with reading MIDI in, (pads_callback).

From my understanding `pads_callback.jl` is somewhat similar to https://github.com/thestk/rtmidi/blob/master/tests/cmidiin.cpp, where the message data of the MIDI event is printed out, via setting a custom callback.

However, when I try this out, I cannot get anything to display. I have verified that I am providing MIDI input, as manually calling rtmidi_get_message while playing MIDI, changes message's value.

I see that the last update was a while ago (to the rtmidi library version you use here (in deps) and this repo), so perhaps my Julia version is causing some issues 
```julia 
julia> versioninfo()
Julia Version 1.7.0-beta3
Commit e76c9dad42 (2021-07-07 08:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin20.5.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, cyclone)
```

Another possibility is that I built a jll repo https://github.com/anandijain/rtmidi_jll.jl from master of https://github.com/thestk/rtmidi so it could be the API changed a bit or something. 

I hope you don't mind but I'm hosting a lightweight copy of your RtMIDI code here https://github.com/anandijain/RtMIDI.jl just so that it can be `]dev`'d.

I'd be super appreciative if you could help me debug and be able to display MIDI input events as they occur to the terminal.

Thanks again for this package

**Comment by wookay** [comment]
yeah.
there are api changes. I opened up this PR.
https://github.com/anandijain/RtMIDI.jl/pull/1

also, I've commented about the rtmidi version. I could not find `5.0.0` at anywhere in the `rtmidi`.
I found `4.0.0` in the header file so you should check that version correctly.
https://github.com/JuliaPackaging/Yggdrasil/pull/3604#pullrequestreview-752318917
